/*
1332. Remove Palindromic Subsequences
https://leetcode.com/problems/remove-palindromic-subsequences/

You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.

STEPS:

*/




const removePalindromeSub = (s) => {
    
    let result = 0;
    
    if (s === s.split('').reverse().join('')) {
        result = 1;
    } else {
        result = 2;
    }

    return result;
};